version: '3.4'

services:
  soundcheckapp:
    image: soundcheckapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8888:8888
