version: '3.4'

services:
  soundcheckapp:
    # image: nielsonderbeke/soundcheckapp:latest
    image: soundcheckapp
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8888:8888
