name: Tests - unit & e2e

on:
  push:
    branches: [ develop ]
  # pull_request:
  #   branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run the app
      run: npm run dev & npx wait-on https://localhost:8888

    - name: Test unit tests
      run: npm run test

    - name: Test e2e tests
      run: npx cypress run --spec "cypress/integration/home.spec.js"
