name: Docker build and push dockerhub

on:
  push:
    branches: [ develop ]
  # pull_request:
  #   branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci
    - run: npm run dev & npx wait-on https://localhost:8888
    - run: npm run test
    - run: npx cypress run

    # - name: Run the app

    # - name: Test unit tests

    # - name: Test e2e tests

    - name: Stop dev server
      run: ^C

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/soundcheckapp:latest
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/soundcheckapp:latest
